# TrafficPulse-X: Synthetic 32-sensor traffic network inspired by METR-LA-style traffic topology.

SENSORS_DATA = [
    {
        "id": "S01",
        "sector": "Sector A",
        "road": "North Highway 1",
        "regionId": "R01",
        "flow": 680,
        "speed": 62,
        "occupancy": 28,
        "health": 0.98,
        "status": "free",
        "active": True,
        "needScore": 0.24,
        "uncertainty": "Low (16%)",
        "expectedBenefit": "3%",
        "expectedBytes": "1.2 KB",
        "lastUpdated": "10 mins ago",
        "lat": 34.0622,
        "lng": -118.2537,
        "x": 16,
        "y": 42
    },
    {
        "id": "S02",
        "sector": "Sector A",
        "road": "North Bypass Connector",
        "regionId": "R01",
        "flow": 1420,
        "speed": 35,
        "occupancy": 55,
        "health": 0.95,
        "status": "moderate",
        "active": True,
        "needScore": 0.58,
        "uncertainty": "Moderate (38%)",
        "expectedBenefit": "9%",
        "expectedBytes": "2.4 KB",
        "lastUpdated": "4 mins ago",
        "lat": 34.0588,
        "lng": -118.2498,
        "x": 27,
        "y": 28
    },
    {
        "id": "S03",
        "sector": "Sector A",
        "road": "Metro Center Bridge",
        "regionId": "R01",
        "flow": 720,
        "speed": 58,
        "occupancy": 31,
        "health": 0.97,
        "status": "free",
        "active": True,
        "needScore": 0.32,
        "uncertainty": "Low (20%)",
        "expectedBenefit": "4%",
        "expectedBytes": "1.6 KB",
        "lastUpdated": "6 mins ago",
        "lat": 34.0645,
        "lng": -118.2389,
        "x": 45,
        "y": 30
    },
    {
        "id": "S04",
        "sector": "Sector B",
        "road": "West Expressway Ramp",
        "regionId": "R02",
        "flow": 980,
        "speed": 48,
        "occupancy": 46,
        "health": 0.96,
        "status": "free",
        "active": True,
        "needScore": 0.41,
        "uncertainty": "Moderate (29%)",
        "expectedBenefit": "6%",
        "expectedBytes": "1.9 KB",
        "lastUpdated": "3 mins ago",
        "lat": 34.0450,
        "lng": -118.2550,
        "x": 12,
        "y": 58
    },
    {
        "id": "S05",
        "sector": "Sector B",
        "road": "Sector A - Main Road",
        "regionId": "R02",
        "flow": 2340,
        "speed": 18,
        "occupancy": 72,
        "health": 0.96,
        "status": "high",
        "active": True,
        "needScore": 0.87,
        "uncertainty": "High (76%)",
        "expectedBenefit": "18%",
        "expectedBytes": "4.2 KB",
        "lastUpdated": "2 minutes ago",
        "lat": 34.0410,
        "lng": -118.2610,
        "x": 42,
        "y": 50
    },
    {
        "id": "S06",
        "sector": "Sector B",
        "road": "Commercial Transit Ave",
        "regionId": "R02",
        "flow": 1160,
        "speed": 40,
        "occupancy": 48,
        "health": 0.94,
        "status": "moderate",
        "active": True,
        "needScore": 0.49,
        "uncertainty": "Moderate (34%)",
        "expectedBenefit": "7%",
        "expectedBytes": "2.1 KB",
        "lastUpdated": "5 mins ago",
        "lat": 34.0480,
        "lng": -118.2680,
        "x": 50,
        "y": 45
    },
    {
        "id": "S07",
        "sector": "Sector C",
        "road": "River East Way",
        "regionId": "R03",
        "flow": 640,
        "speed": 64,
        "occupancy": 24,
        "health": 0.97,
        "status": "free",
        "active": True,
        "needScore": 0.21,
        "uncertainty": "Low (15%)",
        "expectedBenefit": "2%",
        "expectedBytes": "1.1 KB",
        "lastUpdated": "8 mins ago",
        "lat": 34.0320,
        "lng": -118.2320,
        "x": 78,
        "y": 45
    },
    {
        "id": "S08",
        "sector": "Sector B",
        "road": "Figueroa Junction",
        "regionId": "R02",
        "flow": 2110,
        "speed": 20,
        "occupancy": 68,
        "health": 0.94,
        "status": "high",
        "active": True,
        "needScore": 0.72,
        "uncertainty": "High (64%)",
        "expectedBenefit": "14%",
        "expectedBytes": "3.1 KB",
        "lastUpdated": "1 minute ago",
        "hasAlert": True,
        "lat": 34.0380,
        "lng": -118.2660,
        "x": 32,
        "y": 60
    },
    {
        "id": "S09",
        "sector": "Sector C",
        "road": "South Industrial Parkway",
        "regionId": "R03",
        "flow": 710,
        "speed": 56,
        "occupancy": 27,
        "health": 0.96,
        "status": "free",
        "active": True,
        "needScore": 0.28,
        "uncertainty": "Low (18%)",
        "expectedBenefit": "3%",
        "expectedBytes": "1.4 KB",
        "lastUpdated": "7 mins ago",
        "lat": 34.0260,
        "lng": -118.2250,
        "x": 28,
        "y": 70
    },
    {
        "id": "S10",
        "sector": "Sector C",
        "road": "Harbor Freight Ramp",
        "regionId": "R03",
        "flow": 1380,
        "speed": 38,
        "occupancy": 52,
        "health": 0.93,
        "status": "moderate",
        "active": True,
        "needScore": 0.54,
        "uncertainty": "Moderate (36%)",
        "expectedBenefit": "8%",
        "expectedBytes": "2.3 KB",
        "lastUpdated": "3 mins ago",
        "lat": 34.0210,
        "lng": -118.2380,
        "x": 62,
        "y": 75
    },
    {
        "id": "S11",
        "sector": "Sector B",
        "road": "Central Chokepoint",
        "regionId": "R02",
        "flow": 2280,
        "speed": 19,
        "occupancy": 74,
        "health": 0.91,
        "status": "high",
        "active": True,
        "needScore": 0.82,
        "uncertainty": "High (71%)",
        "expectedBenefit": "16%",
        "expectedBytes": "3.8 KB",
        "lastUpdated": "Just now",
        "hasAlert": True,
        "lat": 34.0350,
        "lng": -118.2580,
        "x": 54,
        "y": 66
    },
    {
        "id": "S12",
        "sector": "Sector B",
        "road": "Downtown Tunnel West",
        "regionId": "R02",
        "flow": 890,
        "speed": 55,
        "occupancy": 32,
        "health": 0.98,
        "status": "free",
        "active": True,
        "needScore": 0.31,
        "uncertainty": "Low (19%)",
        "expectedBenefit": "2%",
        "expectedBytes": "1.5 KB",
        "lastUpdated": "4 mins ago",
        "lat": 34.0530,
        "lng": -118.2420,
        "x": 46,
        "y": 72
    }
]

# Directed road network topology with distance, capacity, transition probability
EDGES_DATA = [
    {"from": "S01", "to": "S02", "distanceKm": 1.2, "capacity": 2200, "transitionProb": 0.72, "isCongested": False},
    {"from": "S02", "to": "S03", "distanceKm": 1.6, "capacity": 1800, "transitionProb": 0.28, "isCongested": False},
    {"from": "S01", "to": "S04", "distanceKm": 1.9, "capacity": 2400, "transitionProb": 0.65, "isCongested": False},
    {"from": "S04", "to": "S08", "distanceKm": 1.4, "capacity": 2500, "transitionProb": 0.70, "isCongested": False},
    {"from": "S08", "to": "S05", "distanceKm": 0.9, "capacity": 2800, "transitionProb": 0.85, "isCongested": True},
    {"from": "S05", "to": "S06", "distanceKm": 1.1, "capacity": 2000, "transitionProb": 0.35, "isCongested": True},
    {"from": "S05", "to": "S11", "distanceKm": 0.8, "capacity": 2700, "transitionProb": 0.60, "isCongested": True},
    {"from": "S11", "to": "S10", "distanceKm": 1.5, "capacity": 2200, "transitionProb": 0.55, "isCongested": True},
    {"from": "S06", "to": "S07", "distanceKm": 1.7, "capacity": 1900, "transitionProb": 0.40, "isCongested": False},
    {"from": "S08", "to": "S09", "distanceKm": 2.1, "capacity": 2100, "transitionProb": 0.30, "isCongested": False},
    {"from": "S09", "to": "S12", "distanceKm": 1.3, "capacity": 1900, "transitionProb": 0.65, "isCongested": False},
    {"from": "S12", "to": "S11", "distanceKm": 1.0, "capacity": 2300, "transitionProb": 0.45, "isCongested": False}
]

SYSTEM_EVENTS = [
    {
        "id": "EV-01",
        "time": "18:46",
        "title": "Queried S08 (high uncertainty)",
        "subtitle": "Data received, forecast updated",
        "color": "cyan"
    },
    {
        "id": "EV-02",
        "time": "18:32",
        "title": "Detected congestion at S11",
        "subtitle": "Flow increased by 42%",
        "color": "rose"
    },
    {
        "id": "EV-03",
        "time": "18:20",
        "title": "Skipped S07 (low value)",
        "subtitle": "No significant change expected",
        "color": "slate"
    },
    {
        "id": "EV-04",
        "time": "18:05",
        "title": "Federated update sent (Region 2)",
        "subtitle": "1.8 MB (selected update)",
        "color": "purple"
    }
]
