# TrafficPulse-X: Synthetic 32-sensor traffic network inspired by METR-LA-style traffic topology.

SENSORS_DATA = [   {   'active': True,
        'expectedBenefit': '3%',
        'expectedBytes': '1.2 KB',
        'flow': 680,
        'health': 0.98,
        'id': 'S01',
        'lastUpdated': '10 mins ago',
        'lat': 34.051,
        'lng': -118.252,
        'needScore': 0.24,
        'occupancy': 28,
        'regionId': 'R01',
        'road': 'North Highway 1',
        'sector': 'Sector A',
        'speed': 62,
        'status': 'free',
        'uncertainty': 'Low (16%)',
        'x': 16,
        'y': 42},
    {   'active': True,
        'expectedBenefit': '9%',
        'expectedBytes': '2.4 KB',
        'flow': 1420,
        'health': 0.95,
        'id': 'S02',
        'lastUpdated': '4 mins ago',
        'lat': 34.044,
        'lng': -118.2465,
        'needScore': 0.58,
        'occupancy': 55,
        'regionId': 'R01',
        'road': 'North Bypass Connector',
        'sector': 'Sector A',
        'speed': 35,
        'status': 'moderate',
        'uncertainty': 'Moderate (38%)',
        'x': 27,
        'y': 28},
    {   'active': True,
        'expectedBenefit': '4%',
        'expectedBytes': '1.6 KB',
        'flow': 720,
        'health': 0.97,
        'id': 'S03',
        'lastUpdated': '6 mins ago',
        'lat': 34.045,
        'lng': -118.2375,
        'needScore': 0.32,
        'occupancy': 31,
        'regionId': 'R01',
        'road': 'Metro Center Bridge',
        'sector': 'Sector A',
        'speed': 58,
        'status': 'free',
        'uncertainty': 'Low (20%)',
        'x': 45,
        'y': 30},
    {   'active': True,
        'expectedBenefit': '6%',
        'expectedBytes': '1.9 KB',
        'flow': 980,
        'health': 0.96,
        'id': 'S04',
        'lastUpdated': '3 mins ago',
        'lat': 34.059,
        'lng': -118.254,
        'needScore': 0.41,
        'occupancy': 46,
        'regionId': 'R02',
        'road': 'West Expressway Ramp',
        'sector': 'Sector B',
        'speed': 48,
        'status': 'free',
        'uncertainty': 'Moderate (29%)',
        'x': 12,
        'y': 58},
    {   'active': True,
        'expectedBenefit': '18%',
        'expectedBytes': '4.2 KB',
        'flow': 2340,
        'health': 0.96,
        'id': 'S05',
        'lastUpdated': '2 minutes ago',
        'lat': 34.055,
        'lng': -118.239,
        'needScore': 0.87,
        'occupancy': 72,
        'regionId': 'R02',
        'road': 'Sector A - Main Road',
        'sector': 'Sector B',
        'speed': 18,
        'status': 'high',
        'uncertainty': 'High (76%)',
        'x': 42,
        'y': 50},
    {   'active': True,
        'expectedBenefit': '7%',
        'expectedBytes': '2.1 KB',
        'flow': 1160,
        'health': 0.94,
        'id': 'S06',
        'lastUpdated': '5 mins ago',
        'lat': 34.0525,
        'lng': -118.235,
        'needScore': 0.49,
        'occupancy': 48,
        'regionId': 'R02',
        'road': 'Commercial Transit Ave',
        'sector': 'Sector B',
        'speed': 40,
        'status': 'moderate',
        'uncertainty': 'Moderate (34%)',
        'x': 50,
        'y': 45},
    {   'active': True,
        'expectedBenefit': '2%',
        'expectedBytes': '1.1 KB',
        'flow': 640,
        'health': 0.97,
        'id': 'S07',
        'lastUpdated': '8 mins ago',
        'lat': 34.0525,
        'lng': -118.221,
        'needScore': 0.21,
        'occupancy': 24,
        'regionId': 'R03',
        'road': 'River East Way',
        'sector': 'Sector C',
        'speed': 64,
        'status': 'free',
        'uncertainty': 'Low (15%)',
        'x': 78,
        'y': 45},
    {   'active': True,
        'expectedBenefit': '14%',
        'expectedBytes': '3.1 KB',
        'flow': 2110,
        'hasAlert': True,
        'health': 0.94,
        'id': 'S08',
        'lastUpdated': '1 minute ago',
        'lat': 34.06,
        'lng': -118.244,
        'needScore': 0.72,
        'occupancy': 68,
        'regionId': 'R02',
        'road': 'Figueroa Junction',
        'sector': 'Sector B',
        'speed': 20,
        'status': 'high',
        'uncertainty': 'High (64%)',
        'x': 32,
        'y': 60},
    {   'active': True,
        'expectedBenefit': '3%',
        'expectedBytes': '1.4 KB',
        'flow': 710,
        'health': 0.96,
        'id': 'S09',
        'lastUpdated': '7 mins ago',
        'lat': 34.065,
        'lng': -118.246,
        'needScore': 0.28,
        'occupancy': 27,
        'regionId': 'R03',
        'road': 'South Industrial Parkway',
        'sector': 'Sector C',
        'speed': 56,
        'status': 'free',
        'uncertainty': 'Low (18%)',
        'x': 28,
        'y': 70},
    {   'active': True,
        'expectedBenefit': '8%',
        'expectedBytes': '2.3 KB',
        'flow': 1380,
        'health': 0.93,
        'id': 'S10',
        'lastUpdated': '3 mins ago',
        'lat': 34.0675,
        'lng': -118.229,
        'needScore': 0.54,
        'occupancy': 52,
        'regionId': 'R03',
        'road': 'Harbor Freight Ramp',
        'sector': 'Sector C',
        'speed': 38,
        'status': 'moderate',
        'uncertainty': 'Moderate (36%)',
        'x': 62,
        'y': 75},
    {   'active': True,
        'expectedBenefit': '16%',
        'expectedBytes': '3.8 KB',
        'flow': 2280,
        'hasAlert': True,
        'health': 0.91,
        'id': 'S11',
        'lastUpdated': 'Just now',
        'lat': 34.063,
        'lng': -118.233,
        'needScore': 0.82,
        'occupancy': 74,
        'regionId': 'R02',
        'road': 'Central Chokepoint',
        'sector': 'Sector B',
        'speed': 19,
        'status': 'high',
        'uncertainty': 'High (71%)',
        'x': 54,
        'y': 66},
    {   'active': True,
        'expectedBenefit': '2%',
        'expectedBytes': '1.5 KB',
        'flow': 890,
        'health': 0.98,
        'id': 'S12',
        'lastUpdated': '4 mins ago',
        'lat': 34.066,
        'lng': -118.237,
        'needScore': 0.31,
        'occupancy': 32,
        'regionId': 'R02',
        'road': 'Downtown Tunnel West',
        'sector': 'Sector B',
        'speed': 55,
        'status': 'free',
        'uncertainty': 'Low (19%)',
        'x': 46,
        'y': 72},
    {   'active': True,
        'expectedBenefit': '3%',
        'expectedBytes': '1.3 KB',
        'flow': 620,
        'health': 0.97,
        'id': 'S13',
        'lastUpdated': '9 mins ago',
        'lat': 34.0625,
        'lng': -118.225,
        'needScore': 0.25,
        'occupancy': 22,
        'regionId': 'R03',
        'road': 'East Suburb Corridor',
        'sector': 'Sector C',
        'speed': 60,
        'status': 'free',
        'uncertainty': 'Low (17%)',
        'x': 70,
        'y': 65},
    {   'active': True,
        'expectedBenefit': '7%',
        'expectedBytes': '2.2 KB',
        'flow': 1250,
        'health': 0.95,
        'id': 'S14',
        'lastUpdated': '5 mins ago',
        'lat': 34.06,
        'lng': -118.218,
        'needScore': 0.52,
        'occupancy': 44,
        'regionId': 'R04',
        'road': 'South Canal Bridge',
        'sector': 'Sector D',
        'speed': 42,
        'status': 'moderate',
        'uncertainty': 'Moderate (35%)',
        'x': 84,
        'y': 60},
    {   'active': True,
        'expectedBenefit': '3%',
        'expectedBytes': '1.4 KB',
        'flow': 750,
        'health': 0.98,
        'id': 'S15',
        'lastUpdated': '8 mins ago',
        'lat': 34.0475,
        'lng': -118.216,
        'needScore': 0.27,
        'occupancy': 26,
        'regionId': 'R04',
        'road': 'Cross-Town Bypass',
        'sector': 'Sector D',
        'speed': 58,
        'status': 'free',
        'uncertainty': 'Low (18%)',
        'x': 88,
        'y': 35},
    {   'active': True,
        'expectedBenefit': '2%',
        'expectedBytes': '1.0 KB',
        'flow': 590,
        'health': 0.99,
        'id': 'S16',
        'lastUpdated': '12 mins ago',
        'lat': 34.0375,
        'lng': -118.25,
        'needScore': 0.19,
        'occupancy': 19,
        'regionId': 'R01',
        'road': 'Hillside Parkway',
        'sector': 'Sector A',
        'speed': 65,
        'status': 'free',
        'uncertainty': 'Low (13%)',
        'x': 20,
        'y': 15},
    {   'active': True,
        'expectedBenefit': '4%',
        'expectedBytes': '1.5 KB',
        'flow': 810,
        'health': 0.97,
        'id': 'S17',
        'lastUpdated': '7 mins ago',
        'lat': 34.039,
        'lng': -118.241,
        'needScore': 0.33,
        'occupancy': 30,
        'regionId': 'R01',
        'road': 'Stadium Access Road',
        'sector': 'Sector A',
        'speed': 52,
        'status': 'free',
        'uncertainty': 'Low (21%)',
        'x': 38,
        'y': 18},
    {   'active': True,
        'expectedBenefit': '10%',
        'expectedBytes': '2.6 KB',
        'flow': 1490,
        'health': 0.94,
        'id': 'S18',
        'lastUpdated': '3 mins ago',
        'lat': 34.052,
        'lng': -118.2425,
        'needScore': 0.61,
        'occupancy': 50,
        'regionId': 'R02',
        'road': 'Midtown Underpass',
        'sector': 'Sector B',
        'speed': 36,
        'status': 'moderate',
        'uncertainty': 'Moderate (42%)',
        'x': 35,
        'y': 44},
    {   'active': True,
        'expectedBenefit': '2%',
        'expectedBytes': '1.1 KB',
        'flow': 530,
        'health': 0.98,
        'id': 'S19',
        'lastUpdated': '15 mins ago',
        'lat': 34.0475,
        'lng': -118.2275,
        'needScore': 0.18,
        'occupancy': 18,
        'regionId': 'R03',
        'road': 'Warehouse Spur',
        'sector': 'Sector C',
        'speed': 66,
        'status': 'free',
        'uncertainty': 'Low (12%)',
        'x': 65,
        'y': 35},
    {   'active': True,
        'expectedBenefit': '5%',
        'expectedBytes': '1.8 KB',
        'flow': 920,
        'health': 0.96,
        'id': 'S20',
        'lastUpdated': '6 mins ago',
        'lat': 34.071,
        'lng': -118.2225,
        'needScore': 0.37,
        'occupancy': 34,
        'regionId': 'R04',
        'road': 'Outer Ring South',
        'sector': 'Sector D',
        'speed': 50,
        'status': 'free',
        'uncertainty': 'Low (24%)',
        'x': 75,
        'y': 82},
    {   'active': True,
        'expectedBenefit': '4%',
        'expectedBytes': '1.7 KB',
        'flow': 880,
        'health': 0.97,
        'id': 'S21',
        'lastUpdated': '9 mins ago',
        'lat': 34.068,
        'lng': -118.217,
        'needScore': 0.34,
        'occupancy': 29,
        'regionId': 'R04',
        'road': 'Harbor Freight South',
        'sector': 'Sector D',
        'speed': 54,
        'status': 'free',
        'uncertainty': 'Low (22%)',
        'x': 86,
        'y': 76},
    {   'active': True,
        'expectedBenefit': '8%',
        'expectedBytes': '2.4 KB',
        'flow': 1390,
        'health': 0.95,
        'id': 'S22',
        'lastUpdated': '4 mins ago',
        'lat': 34.0575,
        'lng': -118.231,
        'needScore': 0.56,
        'occupancy': 47,
        'regionId': 'R02',
        'road': 'Market St Connector',
        'sector': 'Sector B',
        'speed': 39,
        'status': 'moderate',
        'uncertainty': 'Moderate (37%)',
        'x': 58,
        'y': 55},
    {   'active': True,
        'expectedBenefit': '3%',
        'expectedBytes': '1.2 KB',
        'flow': 670,
        'health': 0.98,
        'id': 'S23',
        'lastUpdated': '11 mins ago',
        'lat': 34.045,
        'lng': -118.256,
        'needScore': 0.22,
        'occupancy': 21,
        'regionId': 'R01',
        'road': 'North Valley Approach',
        'sector': 'Sector A',
        'speed': 61,
        'status': 'free',
        'uncertainty': 'Low (15%)',
        'x': 8,
        'y': 30},
    {   'active': True,
        'expectedBenefit': '6%',
        'expectedBytes': '2.0 KB',
        'flow': 1110,
        'health': 0.96,
        'id': 'S24',
        'lastUpdated': '5 mins ago',
        'lat': 34.0725,
        'lng': -118.231,
        'needScore': 0.46,
        'occupancy': 41,
        'regionId': 'R03',
        'road': 'Riverfront South',
        'sector': 'Sector C',
        'speed': 44,
        'status': 'moderate',
        'uncertainty': 'Moderate (31%)',
        'x': 58,
        'y': 85},
    {   'active': True,
        'expectedBenefit': '3%',
        'expectedBytes': '1.4 KB',
        'flow': 740,
        'health': 0.97,
        'id': 'S25',
        'lastUpdated': '8 mins ago',
        'lat': 34.073,
        'lng': -118.24,
        'needScore': 0.29,
        'occupancy': 25,
        'regionId': 'R04',
        'road': 'Industrial Park Road',
        'sector': 'Sector D',
        'speed': 57,
        'status': 'free',
        'uncertainty': 'Low (19%)',
        'x': 40,
        'y': 86},
    {   'active': True,
        'expectedBenefit': '4%',
        'expectedBytes': '1.5 KB',
        'flow': 810,
        'health': 0.98,
        'id': 'S26',
        'lastUpdated': '7 mins ago',
        'lat': 34.066,
        'lng': -118.257,
        'needScore': 0.31,
        'occupancy': 28,
        'regionId': 'R01',
        'road': 'Foothill Expressway',
        'sector': 'Sector A',
        'speed': 53,
        'status': 'free',
        'uncertainty': 'Low (20%)',
        'x': 6,
        'y': 72},
    {   'active': True,
        'expectedBenefit': '7%',
        'expectedBytes': '2.3 KB',
        'flow': 1320,
        'health': 0.95,
        'id': 'S27',
        'lastUpdated': '4 mins ago',
        'lat': 34.072,
        'lng': -118.249,
        'needScore': 0.53,
        'occupancy': 45,
        'regionId': 'R02',
        'road': 'Southwest Ramp',
        'sector': 'Sector B',
        'speed': 41,
        'status': 'moderate',
        'uncertainty': 'Moderate (36%)',
        'x': 22,
        'y': 84},
    {   'active': True,
        'expectedBenefit': '3%',
        'expectedBytes': '1.4 KB',
        'flow': 780,
        'health': 0.97,
        'id': 'S28',
        'lastUpdated': '9 mins ago',
        'lat': 34.041,
        'lng': -118.226,
        'needScore': 0.28,
        'occupancy': 23,
        'regionId': 'R03',
        'road': 'Terminal Connector',
        'sector': 'Sector C',
        'speed': 59,
        'status': 'free',
        'uncertainty': 'Low (17%)',
        'x': 68,
        'y': 22},
    {   'active': False,
        'expectedBenefit': '0%',
        'expectedBytes': '0 KB',
        'flow': 0,
        'health': 0.0,
        'id': 'S29',
        'lastUpdated': 'Offline',
        'lat': 34.054,
        'lng': -118.2575,
        'needScore': 0.0,
        'occupancy': 0,
        'regionId': 'R01',
        'road': 'Old Town Gateway',
        'sector': 'Sector A',
        'speed': 0,
        'status': 'inactive',
        'uncertainty': 'N/A',
        'x': 5,
        'y': 48},
    {   'active': False,
        'expectedBenefit': '0%',
        'expectedBytes': '0 KB',
        'flow': 0,
        'health': 0.0,
        'id': 'S30',
        'lastUpdated': 'Offline',
        'lat': 34.04,
        'lng': -118.238,
        'needScore': 0.0,
        'occupancy': 0,
        'regionId': 'R02',
        'road': 'Civic Center Loop',
        'sector': 'Sector B',
        'speed': 0,
        'status': 'inactive',
        'uncertainty': 'N/A',
        'x': 44,
        'y': 20},
    {   'active': False,
        'expectedBenefit': '0%',
        'expectedBytes': '0 KB',
        'flow': 0,
        'health': 0.0,
        'id': 'S31',
        'lastUpdated': 'Offline',
        'lat': 34.056,
        'lng': -118.214,
        'needScore': 0.0,
        'occupancy': 0,
        'regionId': 'R03',
        'road': 'Port Canal Crossing',
        'sector': 'Sector C',
        'speed': 0,
        'status': 'inactive',
        'uncertainty': 'N/A',
        'x': 92,
        'y': 52},
    {   'active': False,
        'expectedBenefit': '0%',
        'expectedBytes': '0 KB',
        'flow': 0,
        'health': 0.0,
        'id': 'S32',
        'lastUpdated': 'Offline',
        'lat': 34.075,
        'lng': -118.214,
        'needScore': 0.0,
        'occupancy': 0,
        'regionId': 'R04',
        'road': 'South Perimeter Node',
        'sector': 'Sector D',
        'speed': 0,
        'status': 'inactive',
        'uncertainty': 'N/A',
        'x': 92,
        'y': 90}]

# Directed road network topology with distance, capacity, transition probability
EDGES_DATA = [
    {"from": "S01", "to": "S02", "distanceKm": 1.2, "capacity": 2200, "transitionProb": 0.72, "isCongested": False},
    {"from": "S02", "to": "S03", "distanceKm": 1.6, "capacity": 1800, "transitionProb": 0.28, "isCongested": False},
    {"from": "S01", "to": "S04", "distanceKm": 1.9, "capacity": 2400, "transitionProb": 0.65, "isCongested": False},
    {"from": "S04", "to": "S08", "distanceKm": 1.4, "capacity": 2500, "transitionProb": 0.70, "isCongested": False},
    {"from": "S08", "to": "S05", "distanceKm": 0.9, "capacity": 2800, "transitionProb": 0.85, "isCongested": True},
    {"from": "S05", "to": "S06", "distanceKm": 1.1, "capacity": 2000, "transitionProb": 0.35, "isCongested": True},
    {"from": "S05", "to": "S11", "distanceKm": 0.8, "capacity": 2700, "transitionProb": 0.60, "isCongested": True},
    {"from": "S11", "to": "S10", "distanceKm": 1.5, "capacity": 2200, "transitionProb": 0.55, "isCongested": True},
    {"from": "S06", "to": "S07", "distanceKm": 1.7, "capacity": 1900, "transitionProb": 0.40, "isCongested": False},
    {"from": "S08", "to": "S09", "distanceKm": 2.1, "capacity": 2100, "transitionProb": 0.30, "isCongested": False},
    {"from": "S09", "to": "S12", "distanceKm": 1.3, "capacity": 1900, "transitionProb": 0.65, "isCongested": False},
    {"from": "S12", "to": "S11", "distanceKm": 1.0, "capacity": 2300, "transitionProb": 0.45, "isCongested": False}
]

SYSTEM_EVENTS = [
    {
        "id": "EV-01",
        "time": "18:46",
        "title": "Queried S08 (high uncertainty)",
        "subtitle": "Data received, forecast updated",
        "color": "cyan"
    },
    {
        "id": "EV-02",
        "time": "18:32",
        "title": "Detected congestion at S11",
        "subtitle": "Flow increased by 42%",
        "color": "rose"
    },
    {
        "id": "EV-03",
        "time": "18:20",
        "title": "Skipped S07 (low value)",
        "subtitle": "No significant change expected",
        "color": "slate"
    },
    {
        "id": "EV-04",
        "time": "18:05",
        "title": "Federated update sent (Region 2)",
        "subtitle": "1.8 MB (selected update)",
        "color": "purple"
    }
]
